import { Bebas_Neue, Noto_Sans_JP, Heebo } from "next/font/google";
import "./globals.css";

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});

const noto = Noto_Sans_JP({
  subsets: ["japanese"],
  weight: ["400"],
  variable: "--font-noto",
});

const heebo = Heebo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-heebo",
});

export const metadata = {
  title: "Arata Ishiguro Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ja"
      className={`${bebas.variable} ${noto.variable} ${heebo.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
